<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>Cockatiel.Example</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Cockatiel/Cockatiel.csproj" />
  </ItemGroup>

</Project>