/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "cockatiel_protobuf.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cockatiel_protobuf_v1_AuthNew, cockatiel_protobuf_v1_AuthNew, 2)


PB_BIND(cockatiel_protobuf_v1_AuthVerify, cockatiel_protobuf_v1_AuthVerify, 2)


PB_BIND(cockatiel_protobuf_v1_Ban, cockatiel_protobuf_v1_Ban, AUTO)


PB_BIND(cockatiel_protobuf_v1_Flag, cockatiel_protobuf_v1_Flag, 2)


PB_BIND(cockatiel_protobuf_v1_Command, cockatiel_protobuf_v1_Command, 4)


PB_BIND(cockatiel_protobuf_v1_Commands, cockatiel_protobuf_v1_Commands, 4)


PB_BIND(cockatiel_protobuf_v1_Commendation, cockatiel_protobuf_v1_Commendation, AUTO)


PB_BIND(cockatiel_protobuf_v1_Reprimand, cockatiel_protobuf_v1_Reprimand, AUTO)


PB_BIND(cockatiel_protobuf_v1_UserStylingTemplate, cockatiel_protobuf_v1_UserStylingTemplate, AUTO)


PB_BIND(cockatiel_protobuf_v1_UserStylingTemplate_CssPropertiesEntry, cockatiel_protobuf_v1_UserStylingTemplate_CssPropertiesEntry, AUTO)


PB_BIND(cockatiel_protobuf_v1_UserData, cockatiel_protobuf_v1_UserData, AUTO)


PB_BIND(cockatiel_protobuf_v1_UserData_PlatformIdsEntry, cockatiel_protobuf_v1_UserData_PlatformIdsEntry, AUTO)


PB_BIND(cockatiel_protobuf_v1_ConnectionRequest, cockatiel_protobuf_v1_ConnectionRequest, AUTO)


PB_BIND(cockatiel_protobuf_v1_ConnectionRequestReturn, cockatiel_protobuf_v1_ConnectionRequestReturn, AUTO)


PB_BIND(cockatiel_protobuf_v1_Err, cockatiel_protobuf_v1_Err, 4)


PB_BIND(cockatiel_protobuf_v1_Log, cockatiel_protobuf_v1_Log, 4)


PB_BIND(cockatiel_protobuf_v1_Shutdown, cockatiel_protobuf_v1_Shutdown, 2)


PB_BIND(cockatiel_protobuf_v1_SendToPlatforms, cockatiel_protobuf_v1_SendToPlatforms, 4)


PB_BIND(cockatiel_protobuf_v1_MessageAck, cockatiel_protobuf_v1_MessageAck, AUTO)


PB_BIND(cockatiel_protobuf_v1_DatabaseQuery, cockatiel_protobuf_v1_DatabaseQuery, 4)


PB_BIND(cockatiel_protobuf_v1_DatabaseQueryResult, cockatiel_protobuf_v1_DatabaseQueryResult, 4)


PB_BIND(cockatiel_protobuf_v1_ModuleControl, cockatiel_protobuf_v1_ModuleControl, AUTO)


PB_BIND(cockatiel_protobuf_v1_ModuleControlResult, cockatiel_protobuf_v1_ModuleControlResult, 4)


PB_BIND(cockatiel_protobuf_v1_Prompt, cockatiel_protobuf_v1_Prompt, 2)


PB_BIND(cockatiel_protobuf_v1_PromptResponse, cockatiel_protobuf_v1_PromptResponse, 4)


PB_BIND(cockatiel_protobuf_v1_AuditFlag, cockatiel_protobuf_v1_AuditFlag, 4)


PB_BIND(cockatiel_protobuf_v1_ChatMessage, cockatiel_protobuf_v1_ChatMessage, 4)


PB_BIND(cockatiel_protobuf_v1_MessagePreProcess, cockatiel_protobuf_v1_MessagePreProcess, 4)


PB_BIND(cockatiel_protobuf_v1_MessageInProcess, cockatiel_protobuf_v1_MessageInProcess, 4)


PB_BIND(cockatiel_protobuf_v1_MessagePostProcess, cockatiel_protobuf_v1_MessagePostProcess, 4)


PB_BIND(cockatiel_protobuf_v1_TimelineEvent, cockatiel_protobuf_v1_TimelineEvent, 4)


PB_BIND(cockatiel_protobuf_v1_Container, cockatiel_protobuf_v1_Container, 4)















