/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_COCKATIEL_PROTOBUF_V1_COCKATIEL_PROTOBUF_PB_H_INCLUDED
#define PB_COCKATIEL_PROTOBUF_V1_COCKATIEL_PROTOBUF_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _cockatiel_protobuf_v1_ProcessPosition {
    cockatiel_protobuf_v1_ProcessPosition_PROCESS_POSITION_UNSPECIFIED = 0,
    cockatiel_protobuf_v1_ProcessPosition_PROCESS_POSITION_PREPROCESS = 1,
    cockatiel_protobuf_v1_ProcessPosition_PROCESS_POSITION_INPROCESS = 2,
    cockatiel_protobuf_v1_ProcessPosition_PROCESS_POSITION_POSTPROCESS = 3,
    cockatiel_protobuf_v1_ProcessPosition_PROCESS_POSITION_CONNECTION = 4
} cockatiel_protobuf_v1_ProcessPosition;

typedef enum _cockatiel_protobuf_v1_FlagLimitType {
    cockatiel_protobuf_v1_FlagLimitType_FLAG_LIMIT_TYPE_UNSPECIFIED = 0,
    cockatiel_protobuf_v1_FlagLimitType_FLAG_LIMIT_TYPE_ANY = 1,
    cockatiel_protobuf_v1_FlagLimitType_FLAG_LIMIT_TYPE_OPTIONS = 2,
    cockatiel_protobuf_v1_FlagLimitType_FLAG_LIMIT_TYPE_RANGE = 3
} cockatiel_protobuf_v1_FlagLimitType;

typedef enum _cockatiel_protobuf_v1_PlatformSendLevel {
    cockatiel_protobuf_v1_PlatformSendLevel_PLATFORM_SEND_LEVEL_UNSPECIFIED = 0,
    cockatiel_protobuf_v1_PlatformSendLevel_PLATFORM_SEND_LEVEL_SELF = 1,
    cockatiel_protobuf_v1_PlatformSendLevel_PLATFORM_SEND_LEVEL_OTHERS = 2,
    cockatiel_protobuf_v1_PlatformSendLevel_PLATFORM_SEND_LEVEL_ALL = 3
} cockatiel_protobuf_v1_PlatformSendLevel;

typedef enum _cockatiel_protobuf_v1_EventCategory {
    cockatiel_protobuf_v1_EventCategory_EVENT_CATEGORY_UNSPECIFIED = 0,
    cockatiel_protobuf_v1_EventCategory_EVENT_CATEGORY_LOG = 1,
    cockatiel_protobuf_v1_EventCategory_EVENT_CATEGORY_WARNING = 2,
    cockatiel_protobuf_v1_EventCategory_EVENT_CATEGORY_ERROR = 3,
    cockatiel_protobuf_v1_EventCategory_EVENT_CATEGORY_SYSTEM = 4,
    cockatiel_protobuf_v1_EventCategory_EVENT_CATEGORY_USER_MESSAGE = 5
} cockatiel_protobuf_v1_EventCategory;

typedef enum _cockatiel_protobuf_v1_ModuleControlAction {
    cockatiel_protobuf_v1_ModuleControlAction_MODULE_CONTROL_ACTION_UNSPECIFIED = 0,
    cockatiel_protobuf_v1_ModuleControlAction_MODULE_CONTROL_ACTION_START = 1,
    cockatiel_protobuf_v1_ModuleControlAction_MODULE_CONTROL_ACTION_STOP = 2,
    cockatiel_protobuf_v1_ModuleControlAction_MODULE_CONTROL_ACTION_DELETE = 3,
    cockatiel_protobuf_v1_ModuleControlAction_MODULE_CONTROL_ACTION_SET_AUTOSTART = 4
} cockatiel_protobuf_v1_ModuleControlAction;

/* What kind of answer a Prompt expects. The UI picks its input widget and
 handling from this; UNSPECIFIED falls back to the legacy behavior
 (input_label empty -> yes/no, non-empty -> free text). */
typedef enum _cockatiel_protobuf_v1_PromptType {
    cockatiel_protobuf_v1_PromptType_PROMPT_TYPE_UNSPECIFIED = 0,
    cockatiel_protobuf_v1_PromptType_PROMPT_TYPE_BOOLEAN = 1, /* yes/no answer (y / n keys) */
    cockatiel_protobuf_v1_PromptType_PROMPT_TYPE_STRING = 2, /* free text: strings, numbers, anything typed/pasted */
    cockatiel_protobuf_v1_PromptType_PROMPT_TYPE_CREDENTIAL = 3 /* like STRING, but the UI must MASK the input */
} cockatiel_protobuf_v1_PromptType;

/* Struct definitions */
typedef struct _cockatiel_protobuf_v1_AuthNew {
    /* expected behavior: 
 unauthed:sever the conenction immedately
 authed: if engine: do nothing. if module: update to new auth */
    char new_auth[512];
} cockatiel_protobuf_v1_AuthNew;

typedef struct _cockatiel_protobuf_v1_AuthVerify {
    /* expected behavior: 
 unauthed: if auth is valid, handle
 authed: if module: do nothing; if engine: check if auth is valid and if so continue. if  not valid sever connection */
    char cur_auth[512];
} cockatiel_protobuf_v1_AuthVerify;

typedef struct _cockatiel_protobuf_v1_Ban {
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: flag the user as banned if user has perms (ie: admin/owner) */
    pb_callback_t commender_uuid7;
    pb_callback_t commendee_uuid7;
    bool unbanned;
    pb_callback_t reason;
    pb_callback_t raw_message;
    pb_callback_t appeals;
} cockatiel_protobuf_v1_Ban;

typedef struct _cockatiel_protobuf_v1_Flag {
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: do nothing */
    char flag_name[128];
    char flag_description[2048];
    cockatiel_protobuf_v1_FlagLimitType limiting_type;
    float min_val;
    float max_val;
    pb_size_t options_count;
    char options[4][64];
} cockatiel_protobuf_v1_Flag;

typedef struct _cockatiel_protobuf_v1_Command {
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: do nothing */
    char command_name[128];
    char command_flag[128];
    char command_description[2048];
    pb_size_t command_flags_count;
    cockatiel_protobuf_v1_Flag command_flags[2];
} cockatiel_protobuf_v1_Command;

typedef struct _cockatiel_protobuf_v1_Commands {
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: add commands to the help registry */
    pb_size_t commands_count;
    cockatiel_protobuf_v1_Command commands[4];
} cockatiel_protobuf_v1_Commands;

typedef struct _cockatiel_protobuf_v1_Commendation {
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: add commendment to the users profile */
    pb_callback_t commender_uuid7;
    pb_callback_t commendee_uuid7;
    pb_callback_t raw_message;
    pb_callback_t reason;
} cockatiel_protobuf_v1_Commendation;

typedef struct _cockatiel_protobuf_v1_Reprimand {
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: add reprimand to user profile */
    pb_callback_t commender_uuid7;
    pb_callback_t commendee_uuid7;
    pb_callback_t raw_message;
    pb_callback_t reason;
} cockatiel_protobuf_v1_Reprimand;

typedef struct _cockatiel_protobuf_v1_UserStylingTemplate {
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: update the users  styling */
    pb_callback_t css_properties;
} cockatiel_protobuf_v1_UserStylingTemplate;

typedef struct _cockatiel_protobuf_v1_UserStylingTemplate_CssPropertiesEntry {
    pb_callback_t key;
    pb_callback_t value;
} cockatiel_protobuf_v1_UserStylingTemplate_CssPropertiesEntry;

typedef struct _cockatiel_protobuf_v1_UserData {
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: do nothing (should be always wrapped) */
    pb_callback_t uuid;
    pb_callback_t username;
    bool is_sponsor;
    bool is_moderator;
    bool is_admin;
    bool is_owner;
    pb_callback_t bans;
    pb_callback_t commendations;
    bool has_styling;
    cockatiel_protobuf_v1_UserStylingTemplate styling;
    pb_callback_t platform_ids;
} cockatiel_protobuf_v1_UserData;

typedef struct _cockatiel_protobuf_v1_UserData_PlatformIdsEntry {
    pb_callback_t key;
    pb_callback_t value;
} cockatiel_protobuf_v1_UserData_PlatformIdsEntry;

typedef struct _cockatiel_protobuf_v1_ConnectionRequest {
    /* expected behavior: 
 unauthed: validate values, if good provide auth token
 authed: do nothing */
    int32_t pin;
    cockatiel_protobuf_v1_ProcessPosition process_position;
    uint32_t priority;
    char module_instance_uuid7[64];
} cockatiel_protobuf_v1_ConnectionRequest;

typedef struct _cockatiel_protobuf_v1_ConnectionRequestReturn {
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: server: do nothing. module: update connection credentials and use moving forward */
    uint32_t new_port;
    char module_instance_uuid7[64];
} cockatiel_protobuf_v1_ConnectionRequestReturn;

typedef PB_BYTES_ARRAY_T(4096) cockatiel_protobuf_v1_Err_blob_t;
typedef struct _cockatiel_protobuf_v1_Err {
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: module: handle liberally. engine: log the error into the timeline database, skip return value from module and pass to next module */
    char log[4096];
    cockatiel_protobuf_v1_Err_blob_t blob;
    char trace[4096];
} cockatiel_protobuf_v1_Err;

typedef PB_BYTES_ARRAY_T(4096) cockatiel_protobuf_v1_Log_blob_t;
typedef struct _cockatiel_protobuf_v1_Log {
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: module: handle liberally. engine: add to timeline then if iexpecting message return, ignore result and carry forth. other just scilently log */
    char log[4096];
    cockatiel_protobuf_v1_Log_blob_t blob;
} cockatiel_protobuf_v1_Log;

typedef struct _cockatiel_protobuf_v1_Shutdown {
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: module: shut self down. engine: do nothing */
    char reason[512];
} cockatiel_protobuf_v1_Shutdown;

typedef struct _cockatiel_protobuf_v1_SendToPlatforms {
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: checked if module has been given the perms to do this, if an adapter-module: send message to platform. if engine: disbatch to adapters.
 The engine verifies the actor (the human who triggered the send) against the
 user database before routing, and logs who sent it to the timeline database. */
    char msg[4096];
    cockatiel_protobuf_v1_PlatformSendLevel level;
    char module_uuid7[64];
    char pid[128];
    char platform[64]; /* target platform ("twitch" | "kick" | "youtube" | "all") */
    char actor_platform[64]; /* identity of the human who triggered the send */
    char actor_handle[128]; /* platform handle of that actor */
    char actor_uuid7[64]; /* user DB uuid7 of that actor (when known) */
} cockatiel_protobuf_v1_SendToPlatforms;

typedef struct _cockatiel_protobuf_v1_MessageAck {
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: engine: mark module as acked for the given message UUID7, remove from pending acks */
    char message_uuid7[64]; /* reserved for future extension (status codes, progress, etc.) */
} cockatiel_protobuf_v1_MessageAck;

typedef struct _cockatiel_protobuf_v1_DatabaseQuery {
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: engine: execute query against the database and return results */
    char query_id[64]; /* unique ID for this query, used to match response */
    char sql[8192]; /* SQL query to execute (read-only) */
    pb_size_t params_count;
    char params[16][2048]; /* query parameters as strings */
} cockatiel_protobuf_v1_DatabaseQuery;

typedef PB_BYTES_ARRAY_T(16384) cockatiel_protobuf_v1_DatabaseQueryResult_result_blob_t;
typedef struct _cockatiel_protobuf_v1_DatabaseQueryResult {
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: module: handle query results */
    char query_id[64]; /* matches the query_id from DatabaseQuery */
    bool success; /* true if query succeeded */
    char error[4096]; /* error message if failed */
    cockatiel_protobuf_v1_DatabaseQueryResult_result_blob_t result_blob; /* serialized result data (JSON) */
} cockatiel_protobuf_v1_DatabaseQueryResult;

typedef struct _cockatiel_protobuf_v1_ModuleControl {
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: engine: start/stop/delete a module or toggle its autostart flag */
    cockatiel_protobuf_v1_ModuleControlAction action;
    char module_name[128];
    bool autostart; /* used only by SET_AUTOSTART */
} cockatiel_protobuf_v1_ModuleControl;

typedef struct _cockatiel_protobuf_v1_ModuleControlResult {
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: module: display result of the control action */
    bool success;
    char error[4096];
    char message[4096];
} cockatiel_protobuf_v1_ModuleControlResult;

typedef struct _cockatiel_protobuf_v1_Prompt {
    /* expected behavior:
 unauthed: sever connection immediately
 authed: module (e.g. the TUI): display the prompt to the user and send a
 PromptResponse back with the same prompt_id_uuid7. engine: forward the
 prompt to connected modules so the user can be asked. */
    char prompt_id_uuid7[64]; /* correlation id for the PromptResponse */
    char prompt[1024]; /* generic title, e.g. "DO YOU WANT TO DO ACTION?" */
    char details[2048]; /* expounding on what the action is */
    char yes_dialog[128]; /* label for the confirm action, e.g. "Allow" */
    char no_dialog[128]; /* label for the deny action, e.g. "Deny" */
    uint32_t timeout; /* seconds the user has to respond */
    char origin[128]; /* who is asking (module name, or "engine") */
    char origin_uuid7[64]; /* optional uuid7 of the origin (e.g. connecting module) */
    char instructions[2048]; /* context / what the user should do / why they're being asked */
    char link[2048]; /* URL to open for the prompt's subject (clickable in the UI) */
    char input_label[128]; /* label for the free-text input field (STRING/CREDENTIAL) */
    cockatiel_protobuf_v1_PromptType prompt_type; /* what kind of answer is expected (see enum above) */
} cockatiel_protobuf_v1_Prompt;

typedef struct _cockatiel_protobuf_v1_PromptResponse {
    /* expected behavior:
 unauthed: sever connection immediately
 authed: module: send back after the user answers a Prompt. engine: route
 the response to whoever is waiting on the prompt_id_uuid7. */
    char prompt_id_uuid7[64];
    bool accepted;
    char reason[4096];
} cockatiel_protobuf_v1_PromptResponse;

typedef struct _cockatiel_protobuf_v1_AuditFlag {
    /* expected behavior:
 unauthed: sever connection immediately
 authed: engine: mark the referenced timeline message as held for audit
 (pipeline_status='audit'); it is NOT shown or counted until a moderator
 reviews it and it is released (resubmitted as normal) or rejected. */
    char message_uuid7[64]; /* the timeline event to hold for audit */
    char reason[4096]; /* why it's being flagged (e.g. language) */
    char origin[128]; /* the module that flagged it */
} cockatiel_protobuf_v1_AuditFlag;

typedef PB_BYTES_ARRAY_T(4096) cockatiel_protobuf_v1_ChatMessage_raw_data_t;
/* Core message data shared across all processing stages */
typedef struct _cockatiel_protobuf_v1_ChatMessage {
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: check add to pre-process queue, after it has been disbatched to each preprocess module put in "inprogress" queue, a then "postprocess" queue */
    char platform[64];
    cockatiel_protobuf_v1_ChatMessage_raw_data_t raw_data;
    char raw_message[4096];
    char user_uuid7[64];
    bool has_command;
    cockatiel_protobuf_v1_Command command;
    bool has_user_data;
    cockatiel_protobuf_v1_UserData user_data;
} cockatiel_protobuf_v1_ChatMessage;

typedef PB_BYTES_ARRAY_T(16384) cockatiel_protobuf_v1_MessagePreProcess_audio_t;
typedef struct _cockatiel_protobuf_v1_MessagePreProcess {
    bool has_raw_message;
    cockatiel_protobuf_v1_ChatMessage raw_message;
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: do nothing */
    char message_uuid7[64];
    cockatiel_protobuf_v1_MessagePreProcess_audio_t audio; /* optional audio rendered for this message (mp3/wav) */
    char audio_type[64]; /* e.g. "audio/mpeg" or "audio/wav" */
} cockatiel_protobuf_v1_MessagePreProcess;

typedef PB_BYTES_ARRAY_T(16384) cockatiel_protobuf_v1_MessageInProcess_audio_t;
typedef struct _cockatiel_protobuf_v1_MessageInProcess {
    bool has_raw_message;
    cockatiel_protobuf_v1_ChatMessage raw_message;
    char processed_message[4096];
    bool abandon_message;
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: do nothing */
    char message_uuid7[64];
    cockatiel_protobuf_v1_MessageInProcess_audio_t audio; /* optional audio rendered for this message (mp3/wav) */
    char audio_type[64]; /* e.g. "audio/mpeg" or "audio/wav" */
} cockatiel_protobuf_v1_MessageInProcess;

typedef PB_BYTES_ARRAY_T(16384) cockatiel_protobuf_v1_MessagePostProcess_audio_t;
typedef struct _cockatiel_protobuf_v1_MessagePostProcess {
    bool has_raw_message;
    cockatiel_protobuf_v1_ChatMessage raw_message;
    char processed_message[4096];
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: do nothing */
    char message_uuid7[64];
    cockatiel_protobuf_v1_MessagePostProcess_audio_t audio; /* optional audio rendered for this message (mp3/wav) */
    char audio_type[64]; /* e.g. "audio/mpeg" or "audio/wav" */
} cockatiel_protobuf_v1_MessagePostProcess;

typedef PB_BYTES_ARRAY_T(16384) cockatiel_protobuf_v1_TimelineEvent_data_blob_t;
typedef struct _cockatiel_protobuf_v1_TimelineEvent {
    /* expected behavior: 
 unauthed: sever connection immediately
 authed: engine: do nothing, module: should not expect, simply drop this UNLESS is a timeline or timelineline backup */
    char timeline_id_uuid7[64]; /* Formerly 'i' - THIS IS THE PRIMARY KEY */
    cockatiel_protobuf_v1_EventCategory event_type; /* Formerly 't' */
    char command_flag[128]; /* Formerly 'c' */
    cockatiel_protobuf_v1_TimelineEvent_data_blob_t data_blob; /* Formerly 'd' */
    char error_message[4096]; /* Formerly 'e' */
    char raw_flags[2048]; /* Formerly 'f' */
    char message_origin[128]; /* Formerly 'o' */
    char stream_origin[128]; /* Formerly 's' */
    char raw_message[4096]; /* Formerly 'r' */
    char processed_message[4096]; /* Formerly 'p' */
    char user_uuid7[64]; /* Formerly 'u' */
    uint32_t version; /* Formerly 'v' (cannot be negative) */
} cockatiel_protobuf_v1_TimelineEvent;

typedef struct _cockatiel_protobuf_v1_Container {
    /* expected behavior: 
 unauthed: process based on other logic
 authed: process based on above logic */
    int32_t version;
    char auth_token[512];
    char module_name[128];
    char module_instance_uuid7[64];
    pb_size_t which_payload;
    union {
        cockatiel_protobuf_v1_ConnectionRequest connection_request;
        cockatiel_protobuf_v1_ConnectionRequestReturn connection_request_return;
        cockatiel_protobuf_v1_AuthVerify auth_verify;
        cockatiel_protobuf_v1_AuthNew auth_new;
        cockatiel_protobuf_v1_Command command_payload;
        cockatiel_protobuf_v1_Commands commands_payload;
        cockatiel_protobuf_v1_MessagePreProcess message_pre_process;
        cockatiel_protobuf_v1_MessageInProcess message_in_process;
        cockatiel_protobuf_v1_MessagePostProcess message_post_process;
        cockatiel_protobuf_v1_TimelineEvent timeline_event;
        cockatiel_protobuf_v1_UserData user_data;
        cockatiel_protobuf_v1_Shutdown shutdown;
        cockatiel_protobuf_v1_Log log;
        cockatiel_protobuf_v1_Err err;
        cockatiel_protobuf_v1_SendToPlatforms send_to_platforms;
        cockatiel_protobuf_v1_MessageAck message_ack;
        cockatiel_protobuf_v1_DatabaseQuery database_query;
        cockatiel_protobuf_v1_DatabaseQueryResult database_query_result;
        cockatiel_protobuf_v1_ModuleControl module_control;
        cockatiel_protobuf_v1_ModuleControlResult module_control_result;
        cockatiel_protobuf_v1_Prompt prompt;
        cockatiel_protobuf_v1_PromptResponse prompt_response;
        cockatiel_protobuf_v1_AuditFlag audit_flag;
    } payload;
} cockatiel_protobuf_v1_Container;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _cockatiel_protobuf_v1_ProcessPosition_MIN cockatiel_protobuf_v1_ProcessPosition_PROCESS_POSITION_UNSPECIFIED
#define _cockatiel_protobuf_v1_ProcessPosition_MAX cockatiel_protobuf_v1_ProcessPosition_PROCESS_POSITION_CONNECTION
#define _cockatiel_protobuf_v1_ProcessPosition_ARRAYSIZE ((cockatiel_protobuf_v1_ProcessPosition)(cockatiel_protobuf_v1_ProcessPosition_PROCESS_POSITION_CONNECTION+1))

#define _cockatiel_protobuf_v1_FlagLimitType_MIN cockatiel_protobuf_v1_FlagLimitType_FLAG_LIMIT_TYPE_UNSPECIFIED
#define _cockatiel_protobuf_v1_FlagLimitType_MAX cockatiel_protobuf_v1_FlagLimitType_FLAG_LIMIT_TYPE_RANGE
#define _cockatiel_protobuf_v1_FlagLimitType_ARRAYSIZE ((cockatiel_protobuf_v1_FlagLimitType)(cockatiel_protobuf_v1_FlagLimitType_FLAG_LIMIT_TYPE_RANGE+1))

#define _cockatiel_protobuf_v1_PlatformSendLevel_MIN cockatiel_protobuf_v1_PlatformSendLevel_PLATFORM_SEND_LEVEL_UNSPECIFIED
#define _cockatiel_protobuf_v1_PlatformSendLevel_MAX cockatiel_protobuf_v1_PlatformSendLevel_PLATFORM_SEND_LEVEL_ALL
#define _cockatiel_protobuf_v1_PlatformSendLevel_ARRAYSIZE ((cockatiel_protobuf_v1_PlatformSendLevel)(cockatiel_protobuf_v1_PlatformSendLevel_PLATFORM_SEND_LEVEL_ALL+1))

#define _cockatiel_protobuf_v1_EventCategory_MIN cockatiel_protobuf_v1_EventCategory_EVENT_CATEGORY_UNSPECIFIED
#define _cockatiel_protobuf_v1_EventCategory_MAX cockatiel_protobuf_v1_EventCategory_EVENT_CATEGORY_USER_MESSAGE
#define _cockatiel_protobuf_v1_EventCategory_ARRAYSIZE ((cockatiel_protobuf_v1_EventCategory)(cockatiel_protobuf_v1_EventCategory_EVENT_CATEGORY_USER_MESSAGE+1))

#define _cockatiel_protobuf_v1_ModuleControlAction_MIN cockatiel_protobuf_v1_ModuleControlAction_MODULE_CONTROL_ACTION_UNSPECIFIED
#define _cockatiel_protobuf_v1_ModuleControlAction_MAX cockatiel_protobuf_v1_ModuleControlAction_MODULE_CONTROL_ACTION_SET_AUTOSTART
#define _cockatiel_protobuf_v1_ModuleControlAction_ARRAYSIZE ((cockatiel_protobuf_v1_ModuleControlAction)(cockatiel_protobuf_v1_ModuleControlAction_MODULE_CONTROL_ACTION_SET_AUTOSTART+1))

#define _cockatiel_protobuf_v1_PromptType_MIN cockatiel_protobuf_v1_PromptType_PROMPT_TYPE_UNSPECIFIED
#define _cockatiel_protobuf_v1_PromptType_MAX cockatiel_protobuf_v1_PromptType_PROMPT_TYPE_CREDENTIAL
#define _cockatiel_protobuf_v1_PromptType_ARRAYSIZE ((cockatiel_protobuf_v1_PromptType)(cockatiel_protobuf_v1_PromptType_PROMPT_TYPE_CREDENTIAL+1))




#define cockatiel_protobuf_v1_Flag_limiting_type_ENUMTYPE cockatiel_protobuf_v1_FlagLimitType









#define cockatiel_protobuf_v1_ConnectionRequest_process_position_ENUMTYPE cockatiel_protobuf_v1_ProcessPosition





#define cockatiel_protobuf_v1_SendToPlatforms_level_ENUMTYPE cockatiel_protobuf_v1_PlatformSendLevel




#define cockatiel_protobuf_v1_ModuleControl_action_ENUMTYPE cockatiel_protobuf_v1_ModuleControlAction


#define cockatiel_protobuf_v1_Prompt_prompt_type_ENUMTYPE cockatiel_protobuf_v1_PromptType







#define cockatiel_protobuf_v1_TimelineEvent_event_type_ENUMTYPE cockatiel_protobuf_v1_EventCategory



/* Initializer values for message structs */
#define cockatiel_protobuf_v1_AuthNew_init_default {""}
#define cockatiel_protobuf_v1_AuthVerify_init_default {""}
#define cockatiel_protobuf_v1_Ban_init_default   {{{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define cockatiel_protobuf_v1_Flag_init_default  {"", "", _cockatiel_protobuf_v1_FlagLimitType_MIN, 0, 0, 0, {"", "", "", ""}}
#define cockatiel_protobuf_v1_Command_init_default {"", "", "", 0, {cockatiel_protobuf_v1_Flag_init_default, cockatiel_protobuf_v1_Flag_init_default}}
#define cockatiel_protobuf_v1_Commands_init_default {0, {cockatiel_protobuf_v1_Command_init_default, cockatiel_protobuf_v1_Command_init_default, cockatiel_protobuf_v1_Command_init_default, cockatiel_protobuf_v1_Command_init_default}}
#define cockatiel_protobuf_v1_Commendation_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define cockatiel_protobuf_v1_Reprimand_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define cockatiel_protobuf_v1_UserStylingTemplate_init_default {{{NULL}, NULL}}
#define cockatiel_protobuf_v1_UserStylingTemplate_CssPropertiesEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define cockatiel_protobuf_v1_UserData_init_default {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, cockatiel_protobuf_v1_UserStylingTemplate_init_default, {{NULL}, NULL}}
#define cockatiel_protobuf_v1_UserData_PlatformIdsEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define cockatiel_protobuf_v1_ConnectionRequest_init_default {0, _cockatiel_protobuf_v1_ProcessPosition_MIN, 0, ""}
#define cockatiel_protobuf_v1_ConnectionRequestReturn_init_default {0, ""}
#define cockatiel_protobuf_v1_Err_init_default   {"", {0, {0}}, ""}
#define cockatiel_protobuf_v1_Log_init_default   {"", {0, {0}}}
#define cockatiel_protobuf_v1_Shutdown_init_default {""}
#define cockatiel_protobuf_v1_SendToPlatforms_init_default {"", _cockatiel_protobuf_v1_PlatformSendLevel_MIN, "", "", "", "", "", ""}
#define cockatiel_protobuf_v1_MessageAck_init_default {""}
#define cockatiel_protobuf_v1_DatabaseQuery_init_default {"", "", 0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}}
#define cockatiel_protobuf_v1_DatabaseQueryResult_init_default {"", 0, "", {0, {0}}}
#define cockatiel_protobuf_v1_ModuleControl_init_default {_cockatiel_protobuf_v1_ModuleControlAction_MIN, "", 0}
#define cockatiel_protobuf_v1_ModuleControlResult_init_default {0, "", ""}
#define cockatiel_protobuf_v1_Prompt_init_default {"", "", "", "", "", 0, "", "", "", "", "", _cockatiel_protobuf_v1_PromptType_MIN}
#define cockatiel_protobuf_v1_PromptResponse_init_default {"", 0, ""}
#define cockatiel_protobuf_v1_AuditFlag_init_default {"", "", ""}
#define cockatiel_protobuf_v1_ChatMessage_init_default {"", {0, {0}}, "", "", false, cockatiel_protobuf_v1_Command_init_default, false, cockatiel_protobuf_v1_UserData_init_default}
#define cockatiel_protobuf_v1_MessagePreProcess_init_default {false, cockatiel_protobuf_v1_ChatMessage_init_default, "", {0, {0}}, ""}
#define cockatiel_protobuf_v1_MessageInProcess_init_default {false, cockatiel_protobuf_v1_ChatMessage_init_default, "", 0, "", {0, {0}}, ""}
#define cockatiel_protobuf_v1_MessagePostProcess_init_default {false, cockatiel_protobuf_v1_ChatMessage_init_default, "", "", {0, {0}}, ""}
#define cockatiel_protobuf_v1_TimelineEvent_init_default {"", _cockatiel_protobuf_v1_EventCategory_MIN, "", {0, {0}}, "", "", "", "", "", "", "", 0}
#define cockatiel_protobuf_v1_Container_init_default {0, "", "", "", 0, {cockatiel_protobuf_v1_ConnectionRequest_init_default}}
#define cockatiel_protobuf_v1_AuthNew_init_zero  {""}
#define cockatiel_protobuf_v1_AuthVerify_init_zero {""}
#define cockatiel_protobuf_v1_Ban_init_zero      {{{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define cockatiel_protobuf_v1_Flag_init_zero     {"", "", _cockatiel_protobuf_v1_FlagLimitType_MIN, 0, 0, 0, {"", "", "", ""}}
#define cockatiel_protobuf_v1_Command_init_zero  {"", "", "", 0, {cockatiel_protobuf_v1_Flag_init_zero, cockatiel_protobuf_v1_Flag_init_zero}}
#define cockatiel_protobuf_v1_Commands_init_zero {0, {cockatiel_protobuf_v1_Command_init_zero, cockatiel_protobuf_v1_Command_init_zero, cockatiel_protobuf_v1_Command_init_zero, cockatiel_protobuf_v1_Command_init_zero}}
#define cockatiel_protobuf_v1_Commendation_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define cockatiel_protobuf_v1_Reprimand_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define cockatiel_protobuf_v1_UserStylingTemplate_init_zero {{{NULL}, NULL}}
#define cockatiel_protobuf_v1_UserStylingTemplate_CssPropertiesEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define cockatiel_protobuf_v1_UserData_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, cockatiel_protobuf_v1_UserStylingTemplate_init_zero, {{NULL}, NULL}}
#define cockatiel_protobuf_v1_UserData_PlatformIdsEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define cockatiel_protobuf_v1_ConnectionRequest_init_zero {0, _cockatiel_protobuf_v1_ProcessPosition_MIN, 0, ""}
#define cockatiel_protobuf_v1_ConnectionRequestReturn_init_zero {0, ""}
#define cockatiel_protobuf_v1_Err_init_zero      {"", {0, {0}}, ""}
#define cockatiel_protobuf_v1_Log_init_zero      {"", {0, {0}}}
#define cockatiel_protobuf_v1_Shutdown_init_zero {""}
#define cockatiel_protobuf_v1_SendToPlatforms_init_zero {"", _cockatiel_protobuf_v1_PlatformSendLevel_MIN, "", "", "", "", "", ""}
#define cockatiel_protobuf_v1_MessageAck_init_zero {""}
#define cockatiel_protobuf_v1_DatabaseQuery_init_zero {"", "", 0, {"", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""}}
#define cockatiel_protobuf_v1_DatabaseQueryResult_init_zero {"", 0, "", {0, {0}}}
#define cockatiel_protobuf_v1_ModuleControl_init_zero {_cockatiel_protobuf_v1_ModuleControlAction_MIN, "", 0}
#define cockatiel_protobuf_v1_ModuleControlResult_init_zero {0, "", ""}
#define cockatiel_protobuf_v1_Prompt_init_zero   {"", "", "", "", "", 0, "", "", "", "", "", _cockatiel_protobuf_v1_PromptType_MIN}
#define cockatiel_protobuf_v1_PromptResponse_init_zero {"", 0, ""}
#define cockatiel_protobuf_v1_AuditFlag_init_zero {"", "", ""}
#define cockatiel_protobuf_v1_ChatMessage_init_zero {"", {0, {0}}, "", "", false, cockatiel_protobuf_v1_Command_init_zero, false, cockatiel_protobuf_v1_UserData_init_zero}
#define cockatiel_protobuf_v1_MessagePreProcess_init_zero {false, cockatiel_protobuf_v1_ChatMessage_init_zero, "", {0, {0}}, ""}
#define cockatiel_protobuf_v1_MessageInProcess_init_zero {false, cockatiel_protobuf_v1_ChatMessage_init_zero, "", 0, "", {0, {0}}, ""}
#define cockatiel_protobuf_v1_MessagePostProcess_init_zero {false, cockatiel_protobuf_v1_ChatMessage_init_zero, "", "", {0, {0}}, ""}
#define cockatiel_protobuf_v1_TimelineEvent_init_zero {"", _cockatiel_protobuf_v1_EventCategory_MIN, "", {0, {0}}, "", "", "", "", "", "", "", 0}
#define cockatiel_protobuf_v1_Container_init_zero {0, "", "", "", 0, {cockatiel_protobuf_v1_ConnectionRequest_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define cockatiel_protobuf_v1_AuthNew_new_auth_tag 1
#define cockatiel_protobuf_v1_AuthVerify_cur_auth_tag 1
#define cockatiel_protobuf_v1_Ban_commender_uuid7_tag 1
#define cockatiel_protobuf_v1_Ban_commendee_uuid7_tag 2
#define cockatiel_protobuf_v1_Ban_unbanned_tag   3
#define cockatiel_protobuf_v1_Ban_reason_tag     4
#define cockatiel_protobuf_v1_Ban_raw_message_tag 5
#define cockatiel_protobuf_v1_Ban_appeals_tag    6
#define cockatiel_protobuf_v1_Flag_flag_name_tag 1
#define cockatiel_protobuf_v1_Flag_flag_description_tag 2
#define cockatiel_protobuf_v1_Flag_limiting_type_tag 3
#define cockatiel_protobuf_v1_Flag_min_val_tag   4
#define cockatiel_protobuf_v1_Flag_max_val_tag   5
#define cockatiel_protobuf_v1_Flag_options_tag   6
#define cockatiel_protobuf_v1_Command_command_name_tag 1
#define cockatiel_protobuf_v1_Command_command_flag_tag 2
#define cockatiel_protobuf_v1_Command_command_description_tag 3
#define cockatiel_protobuf_v1_Command_command_flags_tag 4
#define cockatiel_protobuf_v1_Commands_commands_tag 1
#define cockatiel_protobuf_v1_Commendation_commender_uuid7_tag 1
#define cockatiel_protobuf_v1_Commendation_commendee_uuid7_tag 2
#define cockatiel_protobuf_v1_Commendation_raw_message_tag 3
#define cockatiel_protobuf_v1_Commendation_reason_tag 4
#define cockatiel_protobuf_v1_Reprimand_commender_uuid7_tag 1
#define cockatiel_protobuf_v1_Reprimand_commendee_uuid7_tag 2
#define cockatiel_protobuf_v1_Reprimand_raw_message_tag 3
#define cockatiel_protobuf_v1_Reprimand_reason_tag 4
#define cockatiel_protobuf_v1_UserStylingTemplate_css_properties_tag 1
#define cockatiel_protobuf_v1_UserStylingTemplate_CssPropertiesEntry_key_tag 1
#define cockatiel_protobuf_v1_UserStylingTemplate_CssPropertiesEntry_value_tag 2
#define cockatiel_protobuf_v1_UserData_uuid_tag  1
#define cockatiel_protobuf_v1_UserData_username_tag 2
#define cockatiel_protobuf_v1_UserData_is_sponsor_tag 3
#define cockatiel_protobuf_v1_UserData_is_moderator_tag 4
#define cockatiel_protobuf_v1_UserData_is_admin_tag 5
#define cockatiel_protobuf_v1_UserData_is_owner_tag 6
#define cockatiel_protobuf_v1_UserData_bans_tag  7
#define cockatiel_protobuf_v1_UserData_commendations_tag 8
#define cockatiel_protobuf_v1_UserData_styling_tag 9
#define cockatiel_protobuf_v1_UserData_platform_ids_tag 10
#define cockatiel_protobuf_v1_UserData_PlatformIdsEntry_key_tag 1
#define cockatiel_protobuf_v1_UserData_PlatformIdsEntry_value_tag 2
#define cockatiel_protobuf_v1_ConnectionRequest_pin_tag 1
#define cockatiel_protobuf_v1_ConnectionRequest_process_position_tag 2
#define cockatiel_protobuf_v1_ConnectionRequest_priority_tag 3
#define cockatiel_protobuf_v1_ConnectionRequest_module_instance_uuid7_tag 4
#define cockatiel_protobuf_v1_ConnectionRequestReturn_new_port_tag 1
#define cockatiel_protobuf_v1_ConnectionRequestReturn_module_instance_uuid7_tag 2
#define cockatiel_protobuf_v1_Err_log_tag        1
#define cockatiel_protobuf_v1_Err_blob_tag       2
#define cockatiel_protobuf_v1_Err_trace_tag      3
#define cockatiel_protobuf_v1_Log_log_tag        1
#define cockatiel_protobuf_v1_Log_blob_tag       2
#define cockatiel_protobuf_v1_Shutdown_reason_tag 1
#define cockatiel_protobuf_v1_SendToPlatforms_msg_tag 1
#define cockatiel_protobuf_v1_SendToPlatforms_level_tag 2
#define cockatiel_protobuf_v1_SendToPlatforms_module_uuid7_tag 3
#define cockatiel_protobuf_v1_SendToPlatforms_pid_tag 4
#define cockatiel_protobuf_v1_SendToPlatforms_platform_tag 5
#define cockatiel_protobuf_v1_SendToPlatforms_actor_platform_tag 6
#define cockatiel_protobuf_v1_SendToPlatforms_actor_handle_tag 7
#define cockatiel_protobuf_v1_SendToPlatforms_actor_uuid7_tag 8
#define cockatiel_protobuf_v1_MessageAck_message_uuid7_tag 1
#define cockatiel_protobuf_v1_DatabaseQuery_query_id_tag 1
#define cockatiel_protobuf_v1_DatabaseQuery_sql_tag 2
#define cockatiel_protobuf_v1_DatabaseQuery_params_tag 3
#define cockatiel_protobuf_v1_DatabaseQueryResult_query_id_tag 1
#define cockatiel_protobuf_v1_DatabaseQueryResult_success_tag 2
#define cockatiel_protobuf_v1_DatabaseQueryResult_error_tag 3
#define cockatiel_protobuf_v1_DatabaseQueryResult_result_blob_tag 4
#define cockatiel_protobuf_v1_ModuleControl_action_tag 1
#define cockatiel_protobuf_v1_ModuleControl_module_name_tag 2
#define cockatiel_protobuf_v1_ModuleControl_autostart_tag 3
#define cockatiel_protobuf_v1_ModuleControlResult_success_tag 1
#define cockatiel_protobuf_v1_ModuleControlResult_error_tag 2
#define cockatiel_protobuf_v1_ModuleControlResult_message_tag 3
#define cockatiel_protobuf_v1_Prompt_prompt_id_uuid7_tag 1
#define cockatiel_protobuf_v1_Prompt_prompt_tag  2
#define cockatiel_protobuf_v1_Prompt_details_tag 3
#define cockatiel_protobuf_v1_Prompt_yes_dialog_tag 4
#define cockatiel_protobuf_v1_Prompt_no_dialog_tag 5
#define cockatiel_protobuf_v1_Prompt_timeout_tag 6
#define cockatiel_protobuf_v1_Prompt_origin_tag  7
#define cockatiel_protobuf_v1_Prompt_origin_uuid7_tag 8
#define cockatiel_protobuf_v1_Prompt_instructions_tag 9
#define cockatiel_protobuf_v1_Prompt_link_tag    10
#define cockatiel_protobuf_v1_Prompt_input_label_tag 11
#define cockatiel_protobuf_v1_Prompt_prompt_type_tag 12
#define cockatiel_protobuf_v1_PromptResponse_prompt_id_uuid7_tag 1
#define cockatiel_protobuf_v1_PromptResponse_accepted_tag 2
#define cockatiel_protobuf_v1_PromptResponse_reason_tag 3
#define cockatiel_protobuf_v1_AuditFlag_message_uuid7_tag 1
#define cockatiel_protobuf_v1_AuditFlag_reason_tag 2
#define cockatiel_protobuf_v1_AuditFlag_origin_tag 3
#define cockatiel_protobuf_v1_ChatMessage_platform_tag 1
#define cockatiel_protobuf_v1_ChatMessage_raw_data_tag 2
#define cockatiel_protobuf_v1_ChatMessage_raw_message_tag 3
#define cockatiel_protobuf_v1_ChatMessage_user_uuid7_tag 4
#define cockatiel_protobuf_v1_ChatMessage_command_tag 5
#define cockatiel_protobuf_v1_ChatMessage_user_data_tag 6
#define cockatiel_protobuf_v1_MessagePreProcess_raw_message_tag 1
#define cockatiel_protobuf_v1_MessagePreProcess_message_uuid7_tag 2
#define cockatiel_protobuf_v1_MessagePreProcess_audio_tag 3
#define cockatiel_protobuf_v1_MessagePreProcess_audio_type_tag 4
#define cockatiel_protobuf_v1_MessageInProcess_raw_message_tag 1
#define cockatiel_protobuf_v1_MessageInProcess_processed_message_tag 2
#define cockatiel_protobuf_v1_MessageInProcess_abandon_message_tag 3
#define cockatiel_protobuf_v1_MessageInProcess_message_uuid7_tag 4
#define cockatiel_protobuf_v1_MessageInProcess_audio_tag 5
#define cockatiel_protobuf_v1_MessageInProcess_audio_type_tag 6
#define cockatiel_protobuf_v1_MessagePostProcess_raw_message_tag 1
#define cockatiel_protobuf_v1_MessagePostProcess_processed_message_tag 2
#define cockatiel_protobuf_v1_MessagePostProcess_message_uuid7_tag 3
#define cockatiel_protobuf_v1_MessagePostProcess_audio_tag 4
#define cockatiel_protobuf_v1_MessagePostProcess_audio_type_tag 5
#define cockatiel_protobuf_v1_TimelineEvent_timeline_id_uuid7_tag 1
#define cockatiel_protobuf_v1_TimelineEvent_event_type_tag 2
#define cockatiel_protobuf_v1_TimelineEvent_command_flag_tag 3
#define cockatiel_protobuf_v1_TimelineEvent_data_blob_tag 4
#define cockatiel_protobuf_v1_TimelineEvent_error_message_tag 5
#define cockatiel_protobuf_v1_TimelineEvent_raw_flags_tag 6
#define cockatiel_protobuf_v1_TimelineEvent_message_origin_tag 7
#define cockatiel_protobuf_v1_TimelineEvent_stream_origin_tag 8
#define cockatiel_protobuf_v1_TimelineEvent_raw_message_tag 9
#define cockatiel_protobuf_v1_TimelineEvent_processed_message_tag 10
#define cockatiel_protobuf_v1_TimelineEvent_user_uuid7_tag 11
#define cockatiel_protobuf_v1_TimelineEvent_version_tag 12
#define cockatiel_protobuf_v1_Container_version_tag 1
#define cockatiel_protobuf_v1_Container_auth_token_tag 3
#define cockatiel_protobuf_v1_Container_module_name_tag 4
#define cockatiel_protobuf_v1_Container_module_instance_uuid7_tag 5
#define cockatiel_protobuf_v1_Container_connection_request_tag 7
#define cockatiel_protobuf_v1_Container_connection_request_return_tag 8
#define cockatiel_protobuf_v1_Container_auth_verify_tag 9
#define cockatiel_protobuf_v1_Container_auth_new_tag 10
#define cockatiel_protobuf_v1_Container_command_payload_tag 11
#define cockatiel_protobuf_v1_Container_commands_payload_tag 12
#define cockatiel_protobuf_v1_Container_message_pre_process_tag 13
#define cockatiel_protobuf_v1_Container_message_in_process_tag 14
#define cockatiel_protobuf_v1_Container_message_post_process_tag 15
#define cockatiel_protobuf_v1_Container_timeline_event_tag 16
#define cockatiel_protobuf_v1_Container_user_data_tag 17
#define cockatiel_protobuf_v1_Container_shutdown_tag 18
#define cockatiel_protobuf_v1_Container_log_tag  19
#define cockatiel_protobuf_v1_Container_err_tag  20
#define cockatiel_protobuf_v1_Container_send_to_platforms_tag 21
#define cockatiel_protobuf_v1_Container_message_ack_tag 22
#define cockatiel_protobuf_v1_Container_database_query_tag 23
#define cockatiel_protobuf_v1_Container_database_query_result_tag 24
#define cockatiel_protobuf_v1_Container_module_control_tag 25
#define cockatiel_protobuf_v1_Container_module_control_result_tag 26
#define cockatiel_protobuf_v1_Container_prompt_tag 27
#define cockatiel_protobuf_v1_Container_prompt_response_tag 28
#define cockatiel_protobuf_v1_Container_audit_flag_tag 29

/* Struct field encoding specification for nanopb */
#define cockatiel_protobuf_v1_AuthNew_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   new_auth,          1)
#define cockatiel_protobuf_v1_AuthNew_CALLBACK NULL
#define cockatiel_protobuf_v1_AuthNew_DEFAULT NULL

#define cockatiel_protobuf_v1_AuthVerify_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   cur_auth,          1)
#define cockatiel_protobuf_v1_AuthVerify_CALLBACK NULL
#define cockatiel_protobuf_v1_AuthVerify_DEFAULT NULL

#define cockatiel_protobuf_v1_Ban_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   commender_uuid7,   1) \
X(a, CALLBACK, SINGULAR, STRING,   commendee_uuid7,   2) \
X(a, STATIC,   SINGULAR, BOOL,     unbanned,          3) \
X(a, CALLBACK, SINGULAR, STRING,   reason,            4) \
X(a, CALLBACK, SINGULAR, STRING,   raw_message,       5) \
X(a, CALLBACK, REPEATED, STRING,   appeals,           6)
#define cockatiel_protobuf_v1_Ban_CALLBACK pb_default_field_callback
#define cockatiel_protobuf_v1_Ban_DEFAULT NULL

#define cockatiel_protobuf_v1_Flag_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   flag_name,         1) \
X(a, STATIC,   SINGULAR, STRING,   flag_description,   2) \
X(a, STATIC,   SINGULAR, UENUM,    limiting_type,     3) \
X(a, STATIC,   SINGULAR, FLOAT,    min_val,           4) \
X(a, STATIC,   SINGULAR, FLOAT,    max_val,           5) \
X(a, STATIC,   REPEATED, STRING,   options,           6)
#define cockatiel_protobuf_v1_Flag_CALLBACK NULL
#define cockatiel_protobuf_v1_Flag_DEFAULT NULL

#define cockatiel_protobuf_v1_Command_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   command_name,      1) \
X(a, STATIC,   SINGULAR, STRING,   command_flag,      2) \
X(a, STATIC,   SINGULAR, STRING,   command_description,   3) \
X(a, STATIC,   REPEATED, MESSAGE,  command_flags,     4)
#define cockatiel_protobuf_v1_Command_CALLBACK NULL
#define cockatiel_protobuf_v1_Command_DEFAULT NULL
#define cockatiel_protobuf_v1_Command_command_flags_MSGTYPE cockatiel_protobuf_v1_Flag

#define cockatiel_protobuf_v1_Commands_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  commands,          1)
#define cockatiel_protobuf_v1_Commands_CALLBACK NULL
#define cockatiel_protobuf_v1_Commands_DEFAULT NULL
#define cockatiel_protobuf_v1_Commands_commands_MSGTYPE cockatiel_protobuf_v1_Command

#define cockatiel_protobuf_v1_Commendation_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   commender_uuid7,   1) \
X(a, CALLBACK, SINGULAR, STRING,   commendee_uuid7,   2) \
X(a, CALLBACK, SINGULAR, STRING,   raw_message,       3) \
X(a, CALLBACK, SINGULAR, STRING,   reason,            4)
#define cockatiel_protobuf_v1_Commendation_CALLBACK pb_default_field_callback
#define cockatiel_protobuf_v1_Commendation_DEFAULT NULL

#define cockatiel_protobuf_v1_Reprimand_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   commender_uuid7,   1) \
X(a, CALLBACK, SINGULAR, STRING,   commendee_uuid7,   2) \
X(a, CALLBACK, SINGULAR, STRING,   raw_message,       3) \
X(a, CALLBACK, SINGULAR, STRING,   reason,            4)
#define cockatiel_protobuf_v1_Reprimand_CALLBACK pb_default_field_callback
#define cockatiel_protobuf_v1_Reprimand_DEFAULT NULL

#define cockatiel_protobuf_v1_UserStylingTemplate_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  css_properties,    1)
#define cockatiel_protobuf_v1_UserStylingTemplate_CALLBACK pb_default_field_callback
#define cockatiel_protobuf_v1_UserStylingTemplate_DEFAULT NULL
#define cockatiel_protobuf_v1_UserStylingTemplate_css_properties_MSGTYPE cockatiel_protobuf_v1_UserStylingTemplate_CssPropertiesEntry

#define cockatiel_protobuf_v1_UserStylingTemplate_CssPropertiesEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define cockatiel_protobuf_v1_UserStylingTemplate_CssPropertiesEntry_CALLBACK pb_default_field_callback
#define cockatiel_protobuf_v1_UserStylingTemplate_CssPropertiesEntry_DEFAULT NULL

#define cockatiel_protobuf_v1_UserData_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   uuid,              1) \
X(a, CALLBACK, SINGULAR, STRING,   username,          2) \
X(a, STATIC,   SINGULAR, BOOL,     is_sponsor,        3) \
X(a, STATIC,   SINGULAR, BOOL,     is_moderator,      4) \
X(a, STATIC,   SINGULAR, BOOL,     is_admin,          5) \
X(a, STATIC,   SINGULAR, BOOL,     is_owner,          6) \
X(a, CALLBACK, REPEATED, MESSAGE,  bans,              7) \
X(a, CALLBACK, REPEATED, MESSAGE,  commendations,     8) \
X(a, STATIC,   OPTIONAL, MESSAGE,  styling,           9) \
X(a, CALLBACK, REPEATED, MESSAGE,  platform_ids,     10)
#define cockatiel_protobuf_v1_UserData_CALLBACK pb_default_field_callback
#define cockatiel_protobuf_v1_UserData_DEFAULT NULL
#define cockatiel_protobuf_v1_UserData_bans_MSGTYPE cockatiel_protobuf_v1_Ban
#define cockatiel_protobuf_v1_UserData_commendations_MSGTYPE cockatiel_protobuf_v1_Commendation
#define cockatiel_protobuf_v1_UserData_styling_MSGTYPE cockatiel_protobuf_v1_UserStylingTemplate
#define cockatiel_protobuf_v1_UserData_platform_ids_MSGTYPE cockatiel_protobuf_v1_UserData_PlatformIdsEntry

#define cockatiel_protobuf_v1_UserData_PlatformIdsEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define cockatiel_protobuf_v1_UserData_PlatformIdsEntry_CALLBACK pb_default_field_callback
#define cockatiel_protobuf_v1_UserData_PlatformIdsEntry_DEFAULT NULL

#define cockatiel_protobuf_v1_ConnectionRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    pin,               1) \
X(a, STATIC,   SINGULAR, UENUM,    process_position,   2) \
X(a, STATIC,   SINGULAR, UINT32,   priority,          3) \
X(a, STATIC,   SINGULAR, STRING,   module_instance_uuid7,   4)
#define cockatiel_protobuf_v1_ConnectionRequest_CALLBACK NULL
#define cockatiel_protobuf_v1_ConnectionRequest_DEFAULT NULL

#define cockatiel_protobuf_v1_ConnectionRequestReturn_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   new_port,          1) \
X(a, STATIC,   SINGULAR, STRING,   module_instance_uuid7,   2)
#define cockatiel_protobuf_v1_ConnectionRequestReturn_CALLBACK NULL
#define cockatiel_protobuf_v1_ConnectionRequestReturn_DEFAULT NULL

#define cockatiel_protobuf_v1_Err_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   log,               1) \
X(a, STATIC,   SINGULAR, BYTES,    blob,              2) \
X(a, STATIC,   SINGULAR, STRING,   trace,             3)
#define cockatiel_protobuf_v1_Err_CALLBACK NULL
#define cockatiel_protobuf_v1_Err_DEFAULT NULL

#define cockatiel_protobuf_v1_Log_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   log,               1) \
X(a, STATIC,   SINGULAR, BYTES,    blob,              2)
#define cockatiel_protobuf_v1_Log_CALLBACK NULL
#define cockatiel_protobuf_v1_Log_DEFAULT NULL

#define cockatiel_protobuf_v1_Shutdown_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   reason,            1)
#define cockatiel_protobuf_v1_Shutdown_CALLBACK NULL
#define cockatiel_protobuf_v1_Shutdown_DEFAULT NULL

#define cockatiel_protobuf_v1_SendToPlatforms_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   msg,               1) \
X(a, STATIC,   SINGULAR, UENUM,    level,             2) \
X(a, STATIC,   SINGULAR, STRING,   module_uuid7,      3) \
X(a, STATIC,   SINGULAR, STRING,   pid,               4) \
X(a, STATIC,   SINGULAR, STRING,   platform,          5) \
X(a, STATIC,   SINGULAR, STRING,   actor_platform,    6) \
X(a, STATIC,   SINGULAR, STRING,   actor_handle,      7) \
X(a, STATIC,   SINGULAR, STRING,   actor_uuid7,       8)
#define cockatiel_protobuf_v1_SendToPlatforms_CALLBACK NULL
#define cockatiel_protobuf_v1_SendToPlatforms_DEFAULT NULL

#define cockatiel_protobuf_v1_MessageAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   message_uuid7,     1)
#define cockatiel_protobuf_v1_MessageAck_CALLBACK NULL
#define cockatiel_protobuf_v1_MessageAck_DEFAULT NULL

#define cockatiel_protobuf_v1_DatabaseQuery_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   query_id,          1) \
X(a, STATIC,   SINGULAR, STRING,   sql,               2) \
X(a, STATIC,   REPEATED, STRING,   params,            3)
#define cockatiel_protobuf_v1_DatabaseQuery_CALLBACK NULL
#define cockatiel_protobuf_v1_DatabaseQuery_DEFAULT NULL

#define cockatiel_protobuf_v1_DatabaseQueryResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   query_id,          1) \
X(a, STATIC,   SINGULAR, BOOL,     success,           2) \
X(a, STATIC,   SINGULAR, STRING,   error,             3) \
X(a, STATIC,   SINGULAR, BYTES,    result_blob,       4)
#define cockatiel_protobuf_v1_DatabaseQueryResult_CALLBACK NULL
#define cockatiel_protobuf_v1_DatabaseQueryResult_DEFAULT NULL

#define cockatiel_protobuf_v1_ModuleControl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    action,            1) \
X(a, STATIC,   SINGULAR, STRING,   module_name,       2) \
X(a, STATIC,   SINGULAR, BOOL,     autostart,         3)
#define cockatiel_protobuf_v1_ModuleControl_CALLBACK NULL
#define cockatiel_protobuf_v1_ModuleControl_DEFAULT NULL

#define cockatiel_protobuf_v1_ModuleControlResult_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     success,           1) \
X(a, STATIC,   SINGULAR, STRING,   error,             2) \
X(a, STATIC,   SINGULAR, STRING,   message,           3)
#define cockatiel_protobuf_v1_ModuleControlResult_CALLBACK NULL
#define cockatiel_protobuf_v1_ModuleControlResult_DEFAULT NULL

#define cockatiel_protobuf_v1_Prompt_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   prompt_id_uuid7,   1) \
X(a, STATIC,   SINGULAR, STRING,   prompt,            2) \
X(a, STATIC,   SINGULAR, STRING,   details,           3) \
X(a, STATIC,   SINGULAR, STRING,   yes_dialog,        4) \
X(a, STATIC,   SINGULAR, STRING,   no_dialog,         5) \
X(a, STATIC,   SINGULAR, UINT32,   timeout,           6) \
X(a, STATIC,   SINGULAR, STRING,   origin,            7) \
X(a, STATIC,   SINGULAR, STRING,   origin_uuid7,      8) \
X(a, STATIC,   SINGULAR, STRING,   instructions,      9) \
X(a, STATIC,   SINGULAR, STRING,   link,             10) \
X(a, STATIC,   SINGULAR, STRING,   input_label,      11) \
X(a, STATIC,   SINGULAR, UENUM,    prompt_type,      12)
#define cockatiel_protobuf_v1_Prompt_CALLBACK NULL
#define cockatiel_protobuf_v1_Prompt_DEFAULT NULL

#define cockatiel_protobuf_v1_PromptResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   prompt_id_uuid7,   1) \
X(a, STATIC,   SINGULAR, BOOL,     accepted,          2) \
X(a, STATIC,   SINGULAR, STRING,   reason,            3)
#define cockatiel_protobuf_v1_PromptResponse_CALLBACK NULL
#define cockatiel_protobuf_v1_PromptResponse_DEFAULT NULL

#define cockatiel_protobuf_v1_AuditFlag_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   message_uuid7,     1) \
X(a, STATIC,   SINGULAR, STRING,   reason,            2) \
X(a, STATIC,   SINGULAR, STRING,   origin,            3)
#define cockatiel_protobuf_v1_AuditFlag_CALLBACK NULL
#define cockatiel_protobuf_v1_AuditFlag_DEFAULT NULL

#define cockatiel_protobuf_v1_ChatMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   platform,          1) \
X(a, STATIC,   SINGULAR, BYTES,    raw_data,          2) \
X(a, STATIC,   SINGULAR, STRING,   raw_message,       3) \
X(a, STATIC,   SINGULAR, STRING,   user_uuid7,        4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  command,           5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  user_data,         6)
#define cockatiel_protobuf_v1_ChatMessage_CALLBACK NULL
#define cockatiel_protobuf_v1_ChatMessage_DEFAULT NULL
#define cockatiel_protobuf_v1_ChatMessage_command_MSGTYPE cockatiel_protobuf_v1_Command
#define cockatiel_protobuf_v1_ChatMessage_user_data_MSGTYPE cockatiel_protobuf_v1_UserData

#define cockatiel_protobuf_v1_MessagePreProcess_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  raw_message,       1) \
X(a, STATIC,   SINGULAR, STRING,   message_uuid7,     2) \
X(a, STATIC,   SINGULAR, BYTES,    audio,             3) \
X(a, STATIC,   SINGULAR, STRING,   audio_type,        4)
#define cockatiel_protobuf_v1_MessagePreProcess_CALLBACK NULL
#define cockatiel_protobuf_v1_MessagePreProcess_DEFAULT NULL
#define cockatiel_protobuf_v1_MessagePreProcess_raw_message_MSGTYPE cockatiel_protobuf_v1_ChatMessage

#define cockatiel_protobuf_v1_MessageInProcess_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  raw_message,       1) \
X(a, STATIC,   SINGULAR, STRING,   processed_message,   2) \
X(a, STATIC,   SINGULAR, BOOL,     abandon_message,   3) \
X(a, STATIC,   SINGULAR, STRING,   message_uuid7,     4) \
X(a, STATIC,   SINGULAR, BYTES,    audio,             5) \
X(a, STATIC,   SINGULAR, STRING,   audio_type,        6)
#define cockatiel_protobuf_v1_MessageInProcess_CALLBACK NULL
#define cockatiel_protobuf_v1_MessageInProcess_DEFAULT NULL
#define cockatiel_protobuf_v1_MessageInProcess_raw_message_MSGTYPE cockatiel_protobuf_v1_ChatMessage

#define cockatiel_protobuf_v1_MessagePostProcess_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  raw_message,       1) \
X(a, STATIC,   SINGULAR, STRING,   processed_message,   2) \
X(a, STATIC,   SINGULAR, STRING,   message_uuid7,     3) \
X(a, STATIC,   SINGULAR, BYTES,    audio,             4) \
X(a, STATIC,   SINGULAR, STRING,   audio_type,        5)
#define cockatiel_protobuf_v1_MessagePostProcess_CALLBACK NULL
#define cockatiel_protobuf_v1_MessagePostProcess_DEFAULT NULL
#define cockatiel_protobuf_v1_MessagePostProcess_raw_message_MSGTYPE cockatiel_protobuf_v1_ChatMessage

#define cockatiel_protobuf_v1_TimelineEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   timeline_id_uuid7,   1) \
X(a, STATIC,   SINGULAR, UENUM,    event_type,        2) \
X(a, STATIC,   SINGULAR, STRING,   command_flag,      3) \
X(a, STATIC,   SINGULAR, BYTES,    data_blob,         4) \
X(a, STATIC,   SINGULAR, STRING,   error_message,     5) \
X(a, STATIC,   SINGULAR, STRING,   raw_flags,         6) \
X(a, STATIC,   SINGULAR, STRING,   message_origin,    7) \
X(a, STATIC,   SINGULAR, STRING,   stream_origin,     8) \
X(a, STATIC,   SINGULAR, STRING,   raw_message,       9) \
X(a, STATIC,   SINGULAR, STRING,   processed_message,  10) \
X(a, STATIC,   SINGULAR, STRING,   user_uuid7,       11) \
X(a, STATIC,   SINGULAR, UINT32,   version,          12)
#define cockatiel_protobuf_v1_TimelineEvent_CALLBACK NULL
#define cockatiel_protobuf_v1_TimelineEvent_DEFAULT NULL

#define cockatiel_protobuf_v1_Container_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    version,           1) \
X(a, STATIC,   SINGULAR, STRING,   auth_token,        3) \
X(a, STATIC,   SINGULAR, STRING,   module_name,       4) \
X(a, STATIC,   SINGULAR, STRING,   module_instance_uuid7,   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,connection_request,payload.connection_request),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,connection_request_return,payload.connection_request_return),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,auth_verify,payload.auth_verify),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,auth_new,payload.auth_new),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,command_payload,payload.command_payload),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,commands_payload,payload.commands_payload),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,message_pre_process,payload.message_pre_process),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,message_in_process,payload.message_in_process),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,message_post_process,payload.message_post_process),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,timeline_event,payload.timeline_event),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,user_data,payload.user_data),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,shutdown,payload.shutdown),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,log,payload.log),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,err,payload.err),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,send_to_platforms,payload.send_to_platforms),  21) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,message_ack,payload.message_ack),  22) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,database_query,payload.database_query),  23) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,database_query_result,payload.database_query_result),  24) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,module_control,payload.module_control),  25) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,module_control_result,payload.module_control_result),  26) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,prompt,payload.prompt),  27) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,prompt_response,payload.prompt_response),  28) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,audit_flag,payload.audit_flag),  29)
#define cockatiel_protobuf_v1_Container_CALLBACK NULL
#define cockatiel_protobuf_v1_Container_DEFAULT NULL
#define cockatiel_protobuf_v1_Container_payload_connection_request_MSGTYPE cockatiel_protobuf_v1_ConnectionRequest
#define cockatiel_protobuf_v1_Container_payload_connection_request_return_MSGTYPE cockatiel_protobuf_v1_ConnectionRequestReturn
#define cockatiel_protobuf_v1_Container_payload_auth_verify_MSGTYPE cockatiel_protobuf_v1_AuthVerify
#define cockatiel_protobuf_v1_Container_payload_auth_new_MSGTYPE cockatiel_protobuf_v1_AuthNew
#define cockatiel_protobuf_v1_Container_payload_command_payload_MSGTYPE cockatiel_protobuf_v1_Command
#define cockatiel_protobuf_v1_Container_payload_commands_payload_MSGTYPE cockatiel_protobuf_v1_Commands
#define cockatiel_protobuf_v1_Container_payload_message_pre_process_MSGTYPE cockatiel_protobuf_v1_MessagePreProcess
#define cockatiel_protobuf_v1_Container_payload_message_in_process_MSGTYPE cockatiel_protobuf_v1_MessageInProcess
#define cockatiel_protobuf_v1_Container_payload_message_post_process_MSGTYPE cockatiel_protobuf_v1_MessagePostProcess
#define cockatiel_protobuf_v1_Container_payload_timeline_event_MSGTYPE cockatiel_protobuf_v1_TimelineEvent
#define cockatiel_protobuf_v1_Container_payload_user_data_MSGTYPE cockatiel_protobuf_v1_UserData
#define cockatiel_protobuf_v1_Container_payload_shutdown_MSGTYPE cockatiel_protobuf_v1_Shutdown
#define cockatiel_protobuf_v1_Container_payload_log_MSGTYPE cockatiel_protobuf_v1_Log
#define cockatiel_protobuf_v1_Container_payload_err_MSGTYPE cockatiel_protobuf_v1_Err
#define cockatiel_protobuf_v1_Container_payload_send_to_platforms_MSGTYPE cockatiel_protobuf_v1_SendToPlatforms
#define cockatiel_protobuf_v1_Container_payload_message_ack_MSGTYPE cockatiel_protobuf_v1_MessageAck
#define cockatiel_protobuf_v1_Container_payload_database_query_MSGTYPE cockatiel_protobuf_v1_DatabaseQuery
#define cockatiel_protobuf_v1_Container_payload_database_query_result_MSGTYPE cockatiel_protobuf_v1_DatabaseQueryResult
#define cockatiel_protobuf_v1_Container_payload_module_control_MSGTYPE cockatiel_protobuf_v1_ModuleControl
#define cockatiel_protobuf_v1_Container_payload_module_control_result_MSGTYPE cockatiel_protobuf_v1_ModuleControlResult
#define cockatiel_protobuf_v1_Container_payload_prompt_MSGTYPE cockatiel_protobuf_v1_Prompt
#define cockatiel_protobuf_v1_Container_payload_prompt_response_MSGTYPE cockatiel_protobuf_v1_PromptResponse
#define cockatiel_protobuf_v1_Container_payload_audit_flag_MSGTYPE cockatiel_protobuf_v1_AuditFlag

extern const pb_msgdesc_t cockatiel_protobuf_v1_AuthNew_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_AuthVerify_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_Ban_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_Flag_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_Command_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_Commands_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_Commendation_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_Reprimand_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_UserStylingTemplate_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_UserStylingTemplate_CssPropertiesEntry_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_UserData_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_UserData_PlatformIdsEntry_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_ConnectionRequest_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_ConnectionRequestReturn_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_Err_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_Log_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_Shutdown_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_SendToPlatforms_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_MessageAck_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_DatabaseQuery_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_DatabaseQueryResult_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_ModuleControl_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_ModuleControlResult_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_Prompt_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_PromptResponse_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_AuditFlag_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_ChatMessage_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_MessagePreProcess_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_MessageInProcess_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_MessagePostProcess_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_TimelineEvent_msg;
extern const pb_msgdesc_t cockatiel_protobuf_v1_Container_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cockatiel_protobuf_v1_AuthNew_fields &cockatiel_protobuf_v1_AuthNew_msg
#define cockatiel_protobuf_v1_AuthVerify_fields &cockatiel_protobuf_v1_AuthVerify_msg
#define cockatiel_protobuf_v1_Ban_fields &cockatiel_protobuf_v1_Ban_msg
#define cockatiel_protobuf_v1_Flag_fields &cockatiel_protobuf_v1_Flag_msg
#define cockatiel_protobuf_v1_Command_fields &cockatiel_protobuf_v1_Command_msg
#define cockatiel_protobuf_v1_Commands_fields &cockatiel_protobuf_v1_Commands_msg
#define cockatiel_protobuf_v1_Commendation_fields &cockatiel_protobuf_v1_Commendation_msg
#define cockatiel_protobuf_v1_Reprimand_fields &cockatiel_protobuf_v1_Reprimand_msg
#define cockatiel_protobuf_v1_UserStylingTemplate_fields &cockatiel_protobuf_v1_UserStylingTemplate_msg
#define cockatiel_protobuf_v1_UserStylingTemplate_CssPropertiesEntry_fields &cockatiel_protobuf_v1_UserStylingTemplate_CssPropertiesEntry_msg
#define cockatiel_protobuf_v1_UserData_fields &cockatiel_protobuf_v1_UserData_msg
#define cockatiel_protobuf_v1_UserData_PlatformIdsEntry_fields &cockatiel_protobuf_v1_UserData_PlatformIdsEntry_msg
#define cockatiel_protobuf_v1_ConnectionRequest_fields &cockatiel_protobuf_v1_ConnectionRequest_msg
#define cockatiel_protobuf_v1_ConnectionRequestReturn_fields &cockatiel_protobuf_v1_ConnectionRequestReturn_msg
#define cockatiel_protobuf_v1_Err_fields &cockatiel_protobuf_v1_Err_msg
#define cockatiel_protobuf_v1_Log_fields &cockatiel_protobuf_v1_Log_msg
#define cockatiel_protobuf_v1_Shutdown_fields &cockatiel_protobuf_v1_Shutdown_msg
#define cockatiel_protobuf_v1_SendToPlatforms_fields &cockatiel_protobuf_v1_SendToPlatforms_msg
#define cockatiel_protobuf_v1_MessageAck_fields &cockatiel_protobuf_v1_MessageAck_msg
#define cockatiel_protobuf_v1_DatabaseQuery_fields &cockatiel_protobuf_v1_DatabaseQuery_msg
#define cockatiel_protobuf_v1_DatabaseQueryResult_fields &cockatiel_protobuf_v1_DatabaseQueryResult_msg
#define cockatiel_protobuf_v1_ModuleControl_fields &cockatiel_protobuf_v1_ModuleControl_msg
#define cockatiel_protobuf_v1_ModuleControlResult_fields &cockatiel_protobuf_v1_ModuleControlResult_msg
#define cockatiel_protobuf_v1_Prompt_fields &cockatiel_protobuf_v1_Prompt_msg
#define cockatiel_protobuf_v1_PromptResponse_fields &cockatiel_protobuf_v1_PromptResponse_msg
#define cockatiel_protobuf_v1_AuditFlag_fields &cockatiel_protobuf_v1_AuditFlag_msg
#define cockatiel_protobuf_v1_ChatMessage_fields &cockatiel_protobuf_v1_ChatMessage_msg
#define cockatiel_protobuf_v1_MessagePreProcess_fields &cockatiel_protobuf_v1_MessagePreProcess_msg
#define cockatiel_protobuf_v1_MessageInProcess_fields &cockatiel_protobuf_v1_MessageInProcess_msg
#define cockatiel_protobuf_v1_MessagePostProcess_fields &cockatiel_protobuf_v1_MessagePostProcess_msg
#define cockatiel_protobuf_v1_TimelineEvent_fields &cockatiel_protobuf_v1_TimelineEvent_msg
#define cockatiel_protobuf_v1_Container_fields &cockatiel_protobuf_v1_Container_msg

/* Maximum encoded size of messages (where known) */
/* cockatiel_protobuf_v1_Ban_size depends on runtime parameters */
/* cockatiel_protobuf_v1_Commendation_size depends on runtime parameters */
/* cockatiel_protobuf_v1_Reprimand_size depends on runtime parameters */
/* cockatiel_protobuf_v1_UserStylingTemplate_size depends on runtime parameters */
/* cockatiel_protobuf_v1_UserStylingTemplate_CssPropertiesEntry_size depends on runtime parameters */
/* cockatiel_protobuf_v1_UserData_size depends on runtime parameters */
/* cockatiel_protobuf_v1_UserData_PlatformIdsEntry_size depends on runtime parameters */
/* cockatiel_protobuf_v1_ChatMessage_size depends on runtime parameters */
/* cockatiel_protobuf_v1_MessagePreProcess_size depends on runtime parameters */
/* cockatiel_protobuf_v1_MessageInProcess_size depends on runtime parameters */
/* cockatiel_protobuf_v1_MessagePostProcess_size depends on runtime parameters */
/* cockatiel_protobuf_v1_Container_size depends on runtime parameters */
#define COCKATIEL_PROTOBUF_V1_COCKATIEL_PROTOBUF_PB_H_MAX_SIZE cockatiel_protobuf_v1_DatabaseQuery_size
#define cockatiel_protobuf_v1_AuditFlag_size     4293
#define cockatiel_protobuf_v1_AuthNew_size       514
#define cockatiel_protobuf_v1_AuthVerify_size    514
#define cockatiel_protobuf_v1_Command_size       7220
#define cockatiel_protobuf_v1_Commands_size      28892
#define cockatiel_protobuf_v1_ConnectionRequestReturn_size 71
#define cockatiel_protobuf_v1_ConnectionRequest_size 84
#define cockatiel_protobuf_v1_DatabaseQueryResult_size 20553
#define cockatiel_protobuf_v1_DatabaseQuery_size 41059
#define cockatiel_protobuf_v1_Err_size           12295
#define cockatiel_protobuf_v1_Flag_size          2452
#define cockatiel_protobuf_v1_Log_size           8197
#define cockatiel_protobuf_v1_MessageAck_size    65
#define cockatiel_protobuf_v1_ModuleControlResult_size 8198
#define cockatiel_protobuf_v1_ModuleControl_size 134
#define cockatiel_protobuf_v1_PromptResponse_size 4165
#define cockatiel_protobuf_v1_Prompt_size        7834
#define cockatiel_protobuf_v1_SendToPlatforms_size 4620
#define cockatiel_protobuf_v1_Shutdown_size      514
#define cockatiel_protobuf_v1_TimelineEvent_size 31260

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
